# Generated by Django 4.1.7 on 2023-06-12 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0010_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50, verbose_name='Выберите курс')),
                ('course_level', models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], max_length=50)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='material/', verbose_name='Прикрепите файл')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50)),
                ('course_level', models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], max_length=50)),
                ('attendance_day', models.DateField()),
                ('attendance_status', models.CharField(choices=[('-', 'absence'), ('+', 'present')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='grade',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50, verbose_name='Выберите курс'),
        ),
        migrations.AddField(
            model_name='payment',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50, verbose_name='Выберите курс'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_link',
            field=models.FileField(upload_to='material/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(default=0, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Почта', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Имя', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='Номер', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='Почта', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='Имя', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='Номер', max_length=50),
        ),
        migrations.DeleteModel(
            name='Attendace',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.student', verbose_name='Имя студента'),
        ),
    ]
