# Generated by Django 4.1.7 on 2023-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0011_assessment_attendance_remove_course_desciption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], max_length=50, verbose_name='Выберите уровень курса'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], max_length=50, verbose_name='Выберите уровень курса'),
        ),
    ]
