# Generated by Django 4.1.7 on 2023-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0012_alter_assessment_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50, verbose_name='Выберите курс'),
        ),
    ]
