# Generated by Django 4.1.7 on 2023-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0013_alter_material_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], default='Выберите уровень курса', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_level',
            field=models.CharField(choices=[('A1', 'beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermedia'), ('C1', 'Upper-Intermediate')], default='Выберите уровень курса', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.CharField(choices=[('General English', 'Общий английский'), ('Individual lessons', 'Индивидуальные занятия'), ('English for kids', 'Английский для детей'), ('Online lessons', 'Онлайн занятия'), ('IELTS and TOEFL', 'IELTS и TOEFL'), ('EAP', 'Английский для академический целей')], default='Выберите курс', max_length=50, verbose_name='Выберите курс'),
        ),
    ]
